package org.kie.kogito.queries

unit AlertingService;

import org.kie.kogito.rules.DataStream;
import org.kie.kogito.rules.RuleUnitData;

rule IncomingEvent when
   // matches when a temperature higher than 30 °C is registered (OOPath syntax)
   $e : /eventData [ type == "temperature", value >= 30 ] 
then
   System.out.println("incoming event: "+ $e);
   Alert alert = new Alert( "warning", $e.toString() );
   alertData.append( alert );
end

query Warnings
   alerts: /alertData [ severity == "warning" ]
end