package org.kie.kogito.examples;
unit Hello;


import org.kie.kogito.rules.DataSource;
import org.kie.kogito.rules.DataStore;
import org.kie.kogito.rules.RuleUnitData;
import org.kie.kogito.rules.SingletonStore;

declare Hello extends RuleUnitData
  result : SingletonStore<Result> = DataSource.createSingleton()
  persons : DataStore<Person>
end

rule "older than 18"
when
    $r : /result
    $p : /persons[age > 18]
then
    $r.addAdultPersonName("Hello, " + $p.getName());
end

query hello
  $r : /result
end