package org.kie.kogito.examples;
unit Hello;

import java.util.ArrayList;


import org.kie.kogito.rules.DataSource;
import org.kie.kogito.rules.DataStore;
import org.kie.kogito.rules.RuleUnitData;
import org.kie.kogito.rules.SingletonStore;

declare Hello extends RuleUnitData
  resultList : SingletonStore<ArrayList> = DataSource.createSingleton()
  messages : DataStore<String>
end

rule helloWorld
when
    $r : /resultList
    $m : /messages
then
    $r.add($m + " world");
end

query hello
  $r : /resultList
end