package org.example.alerts

unit AlertingService;

import org.kie.kogito.rules.DataStore;
import org.kie.kogito.rules.RuleUnitData;

import org.example.alerts.MyDataStore;

declare Event
   type:  String
   value: int
end

declare Alert
  severity: String
  message:  String
end

declare AlertingService extends RuleUnitData
   eventData: DataStore<Event>
   alertData: MyDataStore<Alert>
end

rule IncomingEvent when
   $e : /eventData [ type == "temperature", value >= 30 ] 
then
   System.out.println("incoming event: "+ $e);
   Alert alert = new Alert( "warning", $e.toString() );
   alertData.add( alert );
end

query Warnings
   alerts: /alertData [ severity == "warning" ]
end